# Monitors Configuration
# The system now automatically detects monitor resolutions and applies appropriate scaling
# You only need to specify monitors here if you want to override the automatic configuration
# Use xrandr --listmonitors to get your monitor's ID
monitors: {}
  # Example manual configuration (optional):
  # HDMI-2:
  #   resolution: 1920x1080
  #   rotate: normal
  #   main: 1
  #   workspaces: [1, 2, 3, 4, 5]
  # eDP-1:
  #   resolution: 1920x1200  # Auto-scaled from 4K
  #   rotate: normal
  #   position: left
  #   workspaces: [6, 7, 8, 9, 0]

# Note: The system will automatically:
# - Detect 4K displays and apply 200% scaling (e.g., 3840x2400 -> 1920x1200)
# - Assign workspaces 1-5 to external monitors, 6-0 to built-in displays
# - Set external monitors as primary, built-in as secondary
    

# Audio
# use pactl list sinks to get your sink's list
audio:
  alsa_output.usb-Corsair_Corsair_VOID_PRO_Wireless_Gaming_Headset-00.analog-stereo:
    alias: Headset
    type: headset
  alsa_output.pci-0000_00_1f.3.hdmi-stereo-extra1:
    alias: Speakers
    type: speakers
  alsa_output.pci-0000_00_1f.3.analog-stereo:
    alias: Internal speakers
    type: speakers
  # blacklist to not using devices on audio rotation with comma separated
  blacklist: alsa_output.usb-Corsa_ir_Components_Inc._Corsair_ST100_Headset_Outpu_t_v0.6-00.analog-stereo


bspc_rules_single_monitor:
  Brave-browser:
    desktop: 1
    follow: on
  Code:
    desktop: 2
    follow: on
  Gnome-terminal:
    desktop: 3
    follow: on
  Spotify:
    desktop: 4
    follow: on

bspc_rules_dual_monitor:
  Brave-browser:
    desktop: 1
    follow: on
  Code:
    desktop: 2
    follow: on
  Gnome-terminal:
    desktop: 3
    follow: on
  Spotify:
    desktop: 4
    follow: on
